# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'rbconfig'
IS_WINDOWS = (RbConfig::CONFIG['host_os'] =~ /mswin|mingw|cygwin/) ? true : false

Vagrant::Config.run do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "precise32"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  # Boot with a GUI so you can see the screen. (Default is headless)
  # config.vm.boot_mode = :gui

  # This can be set to the host name you wish the guest machine to have.
  config.vm.host_name = "proj-name-dev-box"

  # Requires vagrant-hostmaster
  # 
  # Manage custom /etc/hosts entries on both the host OS and guest VMs
  # config.hosts.name = "proj-name.local"

  # Assign this VM to a host-only network IP, allowing you to access it
  # via the IP. Host-only networks can talk to the host machine as well as
  # any other machines on the same network, but cannot be accessed (through this
  # network interface) by any external networks.
  config.vm.network :hostonly, "192.168.33.10"

  # Assign this VM to a bridged network, allowing you to connect directly to a
  # network using the host's network device. This makes the VM appear as another
  # physical device on your network.
  # config.vm.network :bridged

  # Forward a port from the guest to the host, which allows for outside
  # computers to access the VM, whereas host only networking does not.
  config.vm.forward_port 80, 8080     #apache
  # config.vm.forward_port 3306, 3306   #mysql

  # Share an additional folder to the guest VM. The first argument is
  # an identifier, the second is the path on the guest to mount the
  # folder, and the third is the path on the host to the actual folder.
  config.vm.share_folder "proj-name", "/home/vagrant/proj-name", "../src", :nfs => !IS_WINDOWS
  
  # Allows symlinks to be created in the shared folder.
  config.vm.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/proj-name", "1"]

  # Increase the memory available the VM.
  # config.vm.customize ["modifyvm", :id, "--memory", 1024]

  # Requires vagrant-vbguest plugin
  #
  #va set auto_update to false, if you do NOT want to check the correct  
  # VirtualBox guest additions version when booting this machine
  # config.vbguest.auto_update = false

  # Enable provisioning with chef solo, specifying a cookbooks path, roles
  # path, and data_bags path (all relative to this Vagrantfile), and adding 
  # some recipes and/or roles.
  #
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ["cookbooks", "proj-cookbooks"]
    chef.add_recipe "apt"
    chef.add_recipe "apache2"
    chef.add_recipe "apache2::mod_php5"
    # chef.add_recipe "apache2::mod_rewrite"
    chef.add_recipe "main"
    # chef.add_recipe "mysql"
    # chef.add_recipe "mysql::server"
    chef.add_recipe "php"
    # chef.add_recipe "php::module_curl"
    # chef.add_recipe "php::module_mysql"
    chef.add_recipe "vim"

    chef.json = {
      :apache2 => {
        :default_site_enabled => false
      }
      # :mysql => { 
      #   :server_root_password => "root",
      #   :server_repl_password => "root",
      #   :server_debian_password => "root",
      #   :bind_address => "127.0.0.1"
      # }
    }
  end
end
